POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "324234",
  "author": "fdgdfg",
  "url": "https://pomofocus.io/",
  "likes": 235
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test User",
    "password": "securepassword"
}
