POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "324234",
  "author": "fdgdfg",
  "url": "https://pomofocus.io/",
  "likes": 235
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test User",
    "password": "securepassword"
}

###
GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "securepassword"
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2N2M4NTY5OGYwOTMyYmI4MzI3NTZiMzYiLCJpYXQiOjE3NDExOTk2NzAsImV4cCI6MTc0MTIwMzI3MH0.u3H_uiNHgEUSrYCghX12Ohl2QpvWbQIpcuGgs4nopfE
{
  "title": "Secured Blog",
  "author": "Authenticated User",
  "url": "https://example.com/secured",
  "likes": 10
}
